#!/usr/bin/env python
# -*- coding: utf-8
'''
En "textos" guardamos la colección de frases que irán apareciendo
durante la travesía.
'''

textos = [
u'Comienza el viaje',
u'este juego es distinto a todos los anteriores',
u'no se trata de medir tu habilidad',
u'sino tu paciencia y tu temple.',
u'¿Serás capaz de llegar a la luna?',
u'¿Podrás pilotear la nave el tiempo necesario?',
u'Ya lo veremos.',
u'No te preocupes, te acompañaré durante toda tu travesía.',
u'Tengo muchas cosas para contarte.',
u'Antes que nada te recomiendo esquivar los asteroides',
u'la nave es un poco delicada,',
u'y no resistirá más de 11 o 12 impactos.',
u'Así que, no te distraigas jejeje',
u'Notarás que todo se ve un poco antiguo',
u'es porque este es un juego Steampunk.',
u'El Steampunk es un subgénero de la ciencia-ficción',
u'donde todo funciona con vapor (Steam, en inglés)',
u'En el siglo XIX los escritores imaginaron un futuro basado',
u'en la tecnología que conocían.',
u'Era la época de las grandes locomotoras',
u'y los buques impulsados a vapor.',
u'Julio Verne fue uno de los autores más populares',
u'su novela De La Tierra a La Luna se publicó en 1865',
u'en ella, los protagonistas viajaban a la Luna...',
u'¡Dentro de una gran bala de cañón!',
u'Muchos otros imaginaron viajes a la Luna de diversas maneras.',
u'Por ejemplo El Barón de Munch-Hausen,',
u'llega a la Luna trepando una planta',
u'y encuentra allí seres inteligentes',
u'¡Que viven con la cabeza separada del cuerpo!',
u'Muchos imaginaron que en la Luna habitan seres,',
u'se les ha bautizado Selenitas',
u'porque Selene es un antiguo nombre para la Luna',
u'¿Encontraremos selenitas nosotros?',
#34 textos

#Nivel2
'',
'',
u'¡Excelente! Llegamos a un nuevo nivel, ya estamos más cerca.',
u'¿Cómo lo vas llevando?',
u'Mucho cuidado con los asteroides de hielo...',
u'pueden congelar la nave...',
u'Mmm tratemos de que esto no se descontrole',
'',
u'Julio Verne admiraba mucho a otro escritor,',
u'nada menos que Edgar Allan Poe',
u'tanto lo admiraba que decidió escribir...',
u'una continuación de una novela de Poe.',
u'Se llamó La Esfinge de los Hielos',
u'¿La leíste?',
u'La novela original de Poe se llamaba...',
u'Aventuras de Arthur Gordon Pym',
u'Un nombre raro no ? Muchos dicen que era una forma...',
u'de referirse a él mismo...',
u'Edgar Allan Poe... Arthur Gordon Pym',
u'¿No suenan parecidos?',
u'En fin, me dejé llevar...',
u'Otro escritor interesante fue H. G. Wells',
u'en su novela Los Primeros Hombres En La Luna',
u'usa la ciencia ficción como alegoría política',
u'contra el Imperialismo.',
u'Muchas veces un autor de ciencia-ficción escribe',
u'con motivos muy diferentes a lo que parece',
u'Wells también escribió La Guerra De Los Mundos',
u'que seguramente conoces...',
'',
u'El género steampunk no sólo se encuentra en la literatura,',
u'también lo podemos ver en el diseño, en la historieta,',
u'en la música, en la moda, en juegos (como en este caso),',
u'en la televisión y en el cine.',
#68 textos

#Nivel3
'',
'',
u'A pesar del que el steampunk es relativamente nuevo,',
u'la majestuosidad del subgénero y la maleabilidad de este',
u'encajan perfectamente con la moderna cinematografía',
u'ofreciendo, día a día, una mayor cantidad de títulos',
u'donde las características del steampunk',
u'se hacen más notorias.',
u'Sentando las bases de este género en la pantalla grande,',
u'se encuentra una película checa',
u'llamada Una Invención Diabólica.',
u'Karel Zeman, imagina en esta un mundo imposible',
u'basado en las novelas de Julio Verne.',
u'Tiempo después, aparecieron otras películas en varios países',
u'que siguieron este estilo como Master of the World',
u'guionizada por el escritor Richard Matheson.',
u'Otra película, esta vez de animación,',
u'en contemplar este género fue',
u'El castillo en el Cielo de Hayao Miyazaki.',
u'Pero con la película Wild Wild West el steampunk',
u'tomo importancia en las salas de cine,',
u'y a esta película les seguirían muchas otras como',
u'Metrópolis,  Osamu Tezuka, La brújula Dorada y',
u'La Liga de los Hombres Extraordinarios, entre tantas otras.',
u'Resaltando finalmente tan solo aquellas películas',
u'que han marcado al subgénero se debería mencionar a',
u'la película de animación Steamboy que muestra una Inglaterra',
u'en plena revolución industrial y como la aparición de una',
u'fuente de vapor complica la vida del protagonista y otros.',
u'El Castillo Ambulante de Hayao Miyazaki sirvió para acercar',
u'la corriente más fantástica de este subgénero al gran público.',
u'Cerrando la lista, se encuentra la película Adèle y',
u'el misterio de la momia realizada por el cineasta Luc Besson',
u'anclándose en un París alternativo en 1912.',
# 102 textos

# NIVEL 4
'',
'',
u'Esta nave tiene una gran computadora',
u'que funciona con software libre.',
u'Significa que los usuarios tienen',
u'la libertad de ejecutar, copiar, distribuir,',
u'estudiar, modificar y mejorar ese software.',
u'El software libre permite que los estudiantes conozcan',
u'como trabajan los programas y fomenta el interés,',
u'la investigación y el aprendizaje de nuevos conceptos',
u'en el campo de la informática.',
u'El software libre tiene como prioridad al usuario',
u'siendo flexible, adaptable, seguro e inclusivo,',
u'al contrario de otro software cuyo principal',
u'objetivo es el lucro comercial. Por lo general',
u'el software libre está disponible en forma gratuita,',
u'sin embargo la cuestión más importante es su libertad',
u'y la de sus usuarios, no su precio.',
'',
u'¿Sabías que el steampunk es un movimiento creciente?',
u'Debido a eso y a la mentalidad de “hazlo tú mismo”',
u'muchos de los objetos modernos,',
u'que ahora mismo forman parte de la vida cotidiana,',
u'son modificados por entusiastas y artistas',
u'aspirando alcanzar el característico estilo mecánico',
u'por el que el steampunk es conocido.',
u'Ejemplos de estos objetos incluyen teléfonos móviles,',
u'ordenadores personales e incluso guitarras eléctricas,',
u'que gracias a internet,',
u'el lugar donde estos aficionados comparten sus impresiones',
u'y detallan sus trabajos, cada día son más aquellos',
u'que deciden animarse con estas creaciones y cada vez',
u'esta siendo más adaptado a todo tipo de muebles creando así',
u'un fuerte impacto del movimiento steampunk en decoración.',
# 136 textos

# NIVEL 5
'',
'',
u'Lo hiciste muy bien, ya estamos en el nivel final.',
u'Me imagino que ya debes estar un poco cansado,',
u'pero vamos con el último esfuerzo que ya estamos por llegar.',
'',
u'A pesar de que la televisión comparte en esencia',
u'los mismos principios que el cine,',
u'son pocas las series ambientadas en la temática steampunk.',
u'A diferencia de la historieta, que debido a suparalelismo', 
u'con la literatura, el germen steampunk ha sabido propagarse',
u'dentro de este arte con especial relevancia,',
u'siendo en ocasiones, debido a lo visual de sus tramas,',
u'un excelente alimento para la cinematografía.',
u'Al igual que ha ocurrido dentro del mundo cinematográfico,',
u'el atractivo del steampunk no ha pasado desapercibido para',
u'los desarrolladores de la industria de los videojuegos,',
u'que encuentran en este subgénero',
u'un excelente marco donde encuadrar sus títulos.',
'',
'',
u'¡ATENCIÓN!',
u'Ya estamos llegando a destino',
u'estamos a punto de completar el viaje',
u'¡Felicitaciones! Lo lograste.',
u'Espero que te hayas divertido mucho',
u'y que te lleves algunos conocimientos',
u'con vos para siempre.',
u'Fue un gusto enorme compartir esta aventura',
u'nos vemos a la vuelta :)',
u'LUNA en 3......',
u'2.......',
u'1.......',
''
# 170 textos
]
