#!/usr/bin/env python
# -*- coding: utf-8
'''
En "textos" guardamos la colección de frases que irán apareciendo
durante la travesía.
'''

textos = [
u'',
u'Comienza el viaje',
u'este juego es distinto a todos los anteriores',
u'no se trata de medir tu habilidad',
u'sino tu paciencia y tu temple',
u'¿serás capaz de llegar a la luna?',
u'¿podrás pilotear la nave el tiempo necesario?',
u'Ya lo veremos.',
u'No te preocupes, te acompañaré durante toda tu travesía.',
u'Tengo muchas cosas para contarte',
u'Antes que nada te recomiendo esquivar los asteroides',
u'la nave es un poco delicada,',
u'y no resistirá más de 11 o 12 impactos.',
u'Así que, no te distraigas jejeje',
u'Notarás que todo se ve un poco antiguo',
u'es porque este es un juego Steampunk',
u'El Steampunk es un subgénero de la ciencia-ficción',
u'donde todo funciona con vapor (Steam, en inglés)',
u'En el siglo XIX los escritores imaginaron un futuro basado ',
u'en la tecnología que conocían.',
u'Era la época de las grandes locomotoras',
u'y los buques impulsados a vapor.',
u'Julio Verne fue uno de los autores más populares',
u'su novela De la Tierra a la Luna se publicó en 1865',
u'en ella, los protagonistas viajaban a la Luna ...',
u'¡ dentro de una gran bala de cañón !',
u'Muchos otros imaginaron viajes a la Luna de diversas maneras.',
u'por ejemplo El Barón de Munch-Hausen,',
u'llega a la Luna trepando una planta',
u'Y encuentra allí seres inteligentes',
u'¡ que viven con la cabeza separada del cuerpo !',
u'Muchos imaginaron que en la Luna habitan seres',
u'se les ha bautizado Selenitas',
u'porque Selene es un antiguo nombre para la Luna',
u'¿ Encontraremos selenitas nosotros ?',
#34 textos

#Nivel2
'',
'',
u'¡Excelente! llegamos a un nuevo nivel, ya estamos más cerca.',
u'¿Cómo lo vas llevando?',
u'Mucho cuidado con los asteroides de hielo...',
u'pueden congelar la nave...',
u'mmm tratemos de que esto no se descontrole',
'',
u'Julio Verne admiraba mucho a otro escritor.',
u'nada menos que Edgar Allan Poe',
u'tanto lo admiraba que decidió escribir...',
u'una continuación de una novela de Poe.',
u'se llamó La Esfinge de los Hielos',
u'¿La leíste?',
u'La novela original de Poe se llamaba...',
u'Aventuras de Arhur Gordon Pym',
u'Un nombre raro no ? Muchos dicen que era una forma...',
u'de referirse a él mismo...',
u'Edgar Allan Poe... Arthur Gordon Pym',
u'¿ No suenan parecidos ?',
u'En fin, me dejé llevar...',
# SEGUIR
u'Otro escritor interesante fue H.G.Wells',
u'en su novela Los primeros hombres en la Luna',
u'usa la ciencia ficción como alegoría política',
u'contra el Imperialismo.',
u'Muchas veces un autor de ciencia-ficción escribe',
u'con motivos muy diferentes a lo que parece',
u'Wells también escribió La Guerra de los Mundos',
u'que seguramente conoces...',
'',
u'Sin embargo, un año luz es una medida de distancia:',
u'la longitud que recorre la luz moviéndose',
u'a 300.000 kilómetros por segundo',
u'durante un año.',
#68 textos

#Nivel3
'',
'',
u'A veces escucho sobre',
u'proyectos de exploración del espacio',
u'que tienen como objetivo',
u'encontrar otros planetas habitables.',
u'Pienso ¿por qué en vez de buscar un planeta',
u'de repuesto, no cuidamos más y sanamos',
u'el que ya tenemos?',
u'Se pueden hacer muchas cosas por La Tierra.',
'',
u'Por ejemplo,',
u'cambiar el auto por la bici en viajes cortos',
u'o cambiar el ascensor por las escaleras.',
u'De esta forma ahorrás energía',
u'y fortalecés tu salud al mismo tiempo.',
u'Desenchufa todo lo que no uses.',
u'Muchos equipos por más que estén apagados',
u'consumen electricidad.',
u'Usá lamparitas de LED que duran mucho más',
u'que las tradicionales, incluso las fluorescentes,',
u'y consumen menos energía.',
u'Comenzá a usar una bolsa de las compras',
u'en vez de recibir las bolsas plásticas comunes,',
u'que no son biodegradables',
u'y además cuestan dinero extra.',
u'Si cerras la canilla mientras te cepillás los dientes,',
u'ahorrás unos 60 litros de agua potable por mes.',
'',
u'Antes de tirar cualquier cosa a la basura,',
u'pensá si se puede reutilizar,',
u'reciclar o reparar.',
u'La Tierra es nuestra casa',
u'el cambio empieza en vos.',
# 102 textos

# NIVEL 4
'',
'',
u'Esta nave tiene una gran computadora',
u'que funciona con software libre.',
u'Significa que los usuarios tienen',
u'la libertad de ejecutar, copiar, distribuir,',
u'estudiar, modificar y mejorar ese software.',
u'El software libre permite que los estudiantes conozcan',
u'como trabajan los programas y fomenta el interés,',
u'la investigación y el aprendizaje de nuevos conceptos',
u'en el campo de la informática.',
u'El software libre tiene como prioridad al usuario',
u'siendo flexible, adaptable, seguro e inclusivo,',
u'al contrario de otro software cuyo principal',
u'objetivo es el lucro comercial. Por lo general',
u'el software libre está disponible en forma gratuita,',
u'sin embargo la cuestión más importante es su libertad',
u'y la de sus usuarios, no su precio.',
'',
u'¿Sabías que nuestro sol no es único?',
u'La estrella más próxima a La Tierra',
u'luego del Sol es Próxima Centauri,',
u'está a unos 4 años luz de distancia.',
u'Los astrónomos no pueden ver Próxima Centauri',
u'tal como es hoy,',
u'sino tal y como era hace cuatro años.',
u'La galaxia Andrómeda es el objeto más distante',
u'que se puede ver a simple vista, en una',
u'noche despejada y oscura en otoño.',
u'La luz que recibe tu ojo',
u'dejó esa galaxia hace unos 2,6 millones de años.',
u'Si se produjera un gran cambio en Andrómeda mañana,',
u'no lo sabremos hasta dentro de',
u'más de dos millones de años.',
# 136 textos

# NIVEL 5
'',
'',
u'Lo hiciste muy bien, ya estamos en el nivel final.',
u'Me imagino que ya debes estar un poco cansado,',
u'pero vamos con el último esfuerzo que ya estamos por llegar.',
'',
u'¿Sabías que la gravedad no es la misma en cada planeta?,',
u'La gravedad es un fenómeno natural por el cual',
u'los objetos con masa son atraídos entre sí',
u'efecto mayormente observable en la interacción', 
u'entre los planetas, galaxias y demás objetos del universo.',
u'En la superficie de la Tierra, la aceleración',
u'originada por la gravedad es 9,8 m/s², aproximadamente.',
u'La gravedad terrestre es responsable',
u'del movimiento de caída libre de los cuerpos,',
u'el peso depende de la gravedad. Por ejemplo,',
u'en la Luna el peso es unas seis veces menor',
u'que en la Tierra, debido a que la gravedad',
u'en la Luna es también menor (1,62 m/s²).',
'',
'',
u'¡ATENCIÓN!',
u'Ya estamos llegando a destino',
u'estamos a punto de completar el viaje',
u'¡felicitaciones! lo lograste.',
u'Espero que te hayas divertido mucho',
u'y que te lleves algunos conocimientos',
u'con vos para siempre.',
u'Fue un gusto enorme compartir esta aventura',
u'nos vemos a la vuelta :)',
u'LUNA en 3......',
u'2.......',
u'1.......',
''
]
