.TH TierraLuna

.SH NAME
TierraLuna

.SH SYNOPSIS
Tierraluna es un videojuego creado por el Equipo de Huayra GNU/Linux para
 mostrar lo fácil que es programar usando Pilas-Engine.

.SH DESCRIPTION

This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

.PP
 
Tutoriales
.br
    1era. Parte: http://goo.gl/VBlyJu
    2da. Parte: http://goo.gl/DgMSNk
    3era Parte: http://goo.gl/Or9Z3p
    4ta. Parte: http://goo.gl/JopaKk
    5ta. Parte: http://goo.gl/jJikp7

.SH FILES
https://github.com/HuayraLinux/TierraLuna

.SH AUTHOR
Realizado por Diego Accorinti (@diegoacco) para Huayra GNU/Linux
<diegoacco@gmail.com>
2016 Software libre bajo licencia GPL3 


