#!/usr/bin/env python
# -*- coding: utf-8
'''
En "textos" guardamos la colección de frases que irán apareciendo
durante la travesía.
'''
textos = [
u'',
u'Comienza el viaje',
u'este juego es distinto a todos los anteriores',
u'no se trata de medir tu habilidad',
u'sino tu paciencia y tu temple',
u'¿serás capáz de llegar a la luna?',
u'¿podrás pilotear la nave el tiempo necesario?',
u'ya lo veremos.',
u'No te preocupes, te acompañaré durante toda tu travesía.',
u'Tengo muchas cosas para contarte',
u'Antes que nada te recomiendo esquivar los asteroides',
u'hicimos lo mejor que pudimos con la nave,',
u'pero no resistirá más de 19 o 20 impactos.',
u'Así que, no te distraigas jejeje',
u'Vienes de un planeta llamado Tierra, pero',
u'el 70% de su superficie está cubierta por agua',
u'y solamente el 3% de esa agua es potable.',
u'',
u'El término "planeta" viene de la palabra griega planetes,',
u'que significa "errante".',
u'En la antigua Grecia se dieron cuenta',
u'de que había cinco puntos de luz',
u'que se movían a través del resto de las estrellas',
u'fijas en el cielo.',
u'Algunas se movían constantemente hacia adelante,',
u'otras daban marcha atrás.',
u'Nadie sabía por qué, pero aquellos puntos de luz',
u'no parpadeaban como las estrellas',
u'Cada cultura tenía un nombre para',
u'aquellos cinco puntos de luz:',
u'Mercurio, Venus, Marte, Júpiter y Saturno.',
u'Estos cuerpos celestes no viajan a través de las estrellas,',
u'sino que orbitan alrededor del Sol,',
u'la estrella central de nuestro Sistema Solar.',
#34 textos

#Nivel2
'',
'',
u'Excelente! llegamos a un nuevo nivel, ya estamos más cerca.',
u'¿cómo lo vas llevando?',
u'mucho cuidado con los asteorides..',
u'o quedarás flotando en el espacio como una batata sideral.',
u'mmm tratemos de que ésto no se descontrole',
'',
u'Tengo hambre.',
u' Siempre que viajo',
u'llevo un paquete de sandwiches de miga',
u'jamón y queso. mayonesa.',
u'y el mate, no puede faltar el mate',
u'¿te parece raro tomar mate en el espacio?',
u'dale, mientras te cuento sobre constelaciones.',
'',
u'Las estrellas de una constelación no suelen tener',
u'más relación que su proximidad en el cielo',
u'tal como se ven desde la Tierra.',
u'Las estrellas que forman una constelación',
u'pueden no mantener relación entre sí,',
u'ya que algunas están relativamente cerca de la Tierra',
u'y otras se encuentran a distancias mucho mayores',
u'en el espacio. Al verlas desde la tierra forman',
u'figuras que podemos observar.',
'',
u'Las distancias a las estrellas se miden en años luz.',
u'Un año luz equivale a unos 9,5 billones de kilómetros.',
u'La gente confunde un año luz con una medida de tiempo',
u'porque el término contiene la palabra año.',
u'Sin embargo, un año luz es una medida de distancia:',
u'la longitud que recorre la luz moviéndose',
u'a 300.000 kilómetros por segundo',
u'durante un año.',
#68 textos

#Nivel3
'',
'',
u'A veces escucho sobre',
u'proyectos de exploración del espacio',
u'que tienen como objetivo',
u'encontrar otros planetas habitables.',
u'Pienso ¿por qué en vez de buscar un planeta',
u'de repuesto, no cuidamos más y sanamos',
u'el que ya tenemos?',
u'se pueden hacer muchas cosas por La Tierra.',
'',
u'Por ejemplo,',
u'Cambiar el auto por la bici en viajes cortos',
u'o cambiar el ascensor por las escaleras.',
u'De esta forma ahorrás energía',
u'y fortalecés tu salud al mismo tiempo.',
u'Desenchufa todo lo que no uses.',
u'Muchos equipos por más que estén apagados',
u'consumen electricidad.',
u'Usá lamparitas de LED que duran mucho más',
u'que las tradicionales, incluso las fluorescentes,',
u'y consumen menos energía.',
u'Comenzá a usar una bolsa de las compras',
u'en vez de recibir las bolsas plásticas comunes,',
u'que no son biodegradables',
u'y además cuestan dinero extra.',
u'Si cerras la canilla mientras te cepillás los dientes,',
u'ahorrás unos 60 litros de agua potable por mes.',
'',
u'Antes de tirar cualquier cosa a la basura,',
u'pensá si se puede reutilizar,',
u'reciclar o reparar.',
u'La Tierra es nuestra casa',
u'el cambio empieza en vos.',
# 102 textos

# NIVEL 4
'',
'',
u'Esta nave tiene una gran computadora',
u'que funciona con software libre.',
u'significa que los usuarios tienen',
u'la libertad de ejecutar, copiar, distribuir,',
u'estudiar, modificar y mejorar ese software.',
u'El software libre es una cuestión de libertad,',
u'no de precio.',
'',
u'¿sabías que nuestro sol no es único?',
u'La estrella más próxima a La Tierra',
u'luego del Sol es Próxima Centauri,',
u'está a unos 4 años luz de distancia.',
u'Los astrónomos no pueden ver Próxima Centauri',
u'tal como es hoy,',
u'sino tal y como era hace cuatro años.',
u'La galaxia Andrómeda es el objeto más distante',
u'que se puede ver a simple vista, en una',
u'noche despejada y oscura en otoño.',
u'La luz que recibe tu ojo',
u'dejó esa galaxia hace unos 2,6 millones de años.',
u'Si se produjera un gran cambio en Andrómeda mañana,',
u'no lo sabremos hasta dentro de',
u'más de dos millones de años.',
# NIVEL 5
'',
u'¡ATENCIÓN!',
u'Ya estamos llegando a destino',
u'estamos a punto de completar el viaje',
u'¡felicitaciones! lo lograste.',
u'Espero que te hayas divertido mucho',
u'y que te lleves algunos conocimientos',
u'con vos para siempre.',
u'Fue un gusto enorme compartir esta aventura',
u'nos vemos a la vuelta :)',
u'LUNA en 3......',
u'2.......',
u'1.......',
''
]
